-- Additional 30 Pokémon cards
INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id)
VALUES
(70, 'Charmander', 1, 1, 'Lizard Pokémon, starter from Kanto', 'Ember', '30', 'Water', 'None', '1', 46, 1),
(80, 'Wartortle', 2, 2, 'Turtle Pokémon, evolves from Squirtle', 'Water Gun', '40', 'Electric', 'None', '1', 42, 1),
(60, 'Squirtle', 2, 1, 'Tiny Turtle Pokémon, starter from Kanto', 'Bubble', '20', 'Electric', 'None', '1', 7, 1),
(70, 'Ivysaur', 3, 2, 'Seed Pokémon, evolves from Bulbasaur', 'Razor Leaf', '30', 'Fire', 'Water', '2', 30, 1),
(90, 'Venusaur', 3, 3, 'Seed Pokémon, final evolution of Bulbasaur', 'Solar Beam', '60', 'Fire', 'Water', '3', 15, 1),
(60, 'Raichu', 4, 2, 'Mouse Pokémon, evolves from Pikachu', 'Thunder', '60', 'Fighting', 'Steel', '2', 14, 1),
(70, 'Alakazam', 5, 3, 'Psi Pokémon, evolves from Kadabra', 'Confuse Ray', '30', 'Psychic', 'None', '3', 1, 1),
(80, 'Machamp', 3, 3, 'Superpower Pokémon, evolves from Machoke', 'Seismic Toss', '60', 'Psychic', 'None', '3', 8, 1),
(60, 'Hitmonchan', 3, 1, 'Punching Pokémon, martial arts master', 'Special Punch', '40', 'Psychic', 'None', '2', 7, 1),
(70, 'Electrode', 4, 2, 'Ball Pokémon, evolves from Voltorb', 'Explosion', '80', 'Fighting', 'Steel', '1', 21, 1),
(60, 'Magneton', 4, 2, 'Magnet Pokémon, evolves from Magnemite', 'Thunder Wave', '30', 'Fighting', 'Steel', '2', 9, 1),
(80, 'Nidoking', 3, 3, 'Drill Pokémon, evolves from Nidorino', 'Thrash', '50', 'Psychic', 'None', '3', 11, 1),
(70, 'Nidoqueen', 3, 3, 'Drill Pokémon, evolves from Nidorina', 'Mega Punch', '40', 'Psychic', 'None', '3', 12, 1),
(60, 'Clefairy', 3, 1, 'Fairy Pokémon, mystical powers', 'Sing', '0', 'Steel', 'None', '1', 5, 1),
(70, 'Clefable', 3, 2, 'Fairy Pokémon, evolves from Clefairy', 'Metronome', '40', 'Steel', 'None', '2', 6, 1),
(80, 'Kangaskhan', 3, 1, 'Parent Pokémon, Jungle set rare', 'Comet Punch', '20x', 'Fighting', 'None', '3', 5, 2),
(60, 'Pinsir', 3, 1, 'Stag Beetle Pokémon, Jungle set', 'Guillotine', '50', 'Fire', 'None', '2', 6, 2),
(70, 'Venomoth', 3, 2, 'Poison Moth Pokémon, Jungle set', 'Venom Powder', '10', 'Fire', 'None', '1', 13, 2),
(80, 'Vileplume', 3, 3, 'Flower Pokémon, evolves from Gloom', 'Petal Dance', '40x', 'Fire', 'Water', '2', 15, 2),
(60, 'Butterfree', 3, 2, 'Butterfly Pokémon, evolves from Metapod', 'Whirlwind', '20', 'Fire', 'None', '1', 33, 2),
(70, 'Fearow', 3, 2, 'Beak Pokémon, evolves from Spearow', 'Agility', '20', 'Electric', 'None', '1', 36, 2),
(60, 'Dodrio', 3, 2, 'Triple Bird Pokémon, evolves from Doduo', 'Rage', '10+', 'Electric', 'None', '1', 34, 2),
(80, 'Rhydon', 3, 2, 'Drill Pokémon, evolves from Rhyhorn', 'Horn Attack', '30', 'Grass', 'None', '3', 45, 2),
(70, 'Hypno', 5, 2, 'Hypnosis Pokémon, evolves from Drowzee', 'Prophecy', '0', 'Psychic', 'None', '2', 8, 2),
(60, 'Seaking', 2, 2, 'Goldfish Pokémon, evolves from Goldeen', 'Horn Attack', '30', 'Electric', 'None', '1', 44, 2),
(80, 'Lapras', 2, 1, 'Transport Pokémon, Fossil set rare', 'Water Gun', '30+', 'Electric', 'None', '2', 10, 3),
(70, 'Omastar', 2, 2, 'Spiral Pokémon, evolves from Omanyte', 'Hydro Pump', '40+', 'Grass', 'None', '2', 20, 3),
(60, 'Muk', 3, 2, 'Sludge Pokémon, evolves from Grimer', 'Sludge', '30', 'Psychic', 'None', '2', 13, 3),
(90, 'Ditto', 3, 1, 'Transform Pokémon, Fossil set rare', 'Transform', '—', 'Fighting', 'None', '1', 18, 3),
(70, 'Articuno', 2, 1, 'Legendary bird Pokémon of ice', 'Freeze Dry', '30', 'Electric', 'None', '2', 2, 3);
