-- More 30 Pokémon cards
INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id)
VALUES
(50, 'Pidgey', 3, 1, 'Tiny Bird Pokémon, Base Set common', 'Gust', '10', 'Electric', 'None', '1', 57, 1),
(70, 'Pidgeotto', 3, 2, 'Bird Pokémon, evolves from Pidgey', 'Whirlwind', '20', 'Electric', 'None', '1', 17, 1),
(80, 'Pidgeot', 3, 3, 'Bird Pokémon, final evolution', 'Hurricane', '30', 'Electric', 'None', '2', 8, 1),
(60, 'Rattata', 3, 1, 'Mouse Pokémon, Base Set common', 'Bite', '20', 'Fighting', 'None', '1', 61, 1),
(70, 'Raticate', 3, 2, 'Mouse Pokémon, evolves from Rattata', 'Super Fang', '—', 'Fighting', 'None', '1', 40, 1),
(60, 'Ekans', 3, 1, 'Snake Pokémon, Base Set common', 'Wrap', '10', 'Psychic', 'None', '1', 55, 1),
(80, 'Arbok', 3, 2, 'Cobra Pokémon, evolves from Ekans', 'Poison Fang', '30', 'Psychic', 'None', '2', 2, 1),
(70, 'Sandshrew', 3, 1, 'Mouse Pokémon, Base Set common', 'Scratch', '20', 'Water', 'None', '1', 64, 1),
(80, 'Sandslash', 3, 2, 'Mouse Pokémon, evolves from Sandshrew', 'Slash', '30', 'Water', 'None', '2', 31, 1),
(60, 'Diglett', 3, 1, 'Mole Pokémon, Base Set common', 'Dig', '10', 'Grass', 'None', '1', 47, 1),
(70, 'Dugtrio', 3, 2, 'Mole Pokémon, evolves from Diglett', 'Earthquake', '40', 'Grass', 'None', '2', 19, 1),
(60, 'Geodude', 3, 1, 'Rock Pokémon, Fossil set', 'Tackle', '10', 'Grass', 'None', '1', 37, 3),
(80, 'Graveler', 3, 2, 'Rock Pokémon, evolves from Geodude', 'Rock Throw', '30', 'Grass', 'None', '2', 36, 3),
(100, 'Golem', 3, 3, 'Megaton Pokémon, evolves from Graveler', 'Explosion', '80', 'Grass', 'None', '3', 37, 3),
(70, 'Onix', 3, 1, 'Rock Snake Pokémon, Fossil set', 'Rock Throw', '10', 'Grass', 'None', '3', 56, 3),
(60, 'Cubone', 3, 1, 'Lonely Pokémon, Fossil set', 'Bone Attack', '20', 'Grass', 'None', '1', 50, 3),
(80, 'Marowak', 3, 2, 'Bone Keeper Pokémon, evolves from Cubone', 'Bonemerang', '30x', 'Grass', 'None', '2', 39, 3),
(70, 'Horsea', 2, 1, 'Dragon Pokémon, Fossil set', 'Smokescreen', '10', 'Electric', 'None', '1', 50, 3),
(80, 'Seadra', 2, 2, 'Dragon Pokémon, evolves from Horsea', 'Water Gun', '30+', 'Electric', 'None', '2', 42, 3),
(100, 'Kingdra', 2, 3, 'Dragon Pokémon, evolves from Seadra', 'Dragon Breath', '60', 'Electric', 'None', '3', 43, 3),
(60, 'Krabby', 2, 1, 'River Crab Pokémon, Fossil set', 'Vice Grip', '20', 'Electric', 'None', '1', 51, 3),
(80, 'Kingler', 2, 2, 'Pincer Pokémon, evolves from Krabby', 'Crabhammer', '50', 'Electric', 'None', '2', 32, 3),
(70, 'Staryu', 2, 1, 'Star Shape Pokémon, Base Set', 'Slap', '20', 'Electric', 'None', '1', 65, 1),
(80, 'Starmie', 2, 2, 'Mysterious Pokémon, evolves from Staryu', 'Recover', '—', 'Electric', 'None', '1', 64, 1),
(60, 'Shellder', 2, 1, 'Bivalve Pokémon, Base Set', 'Clamp', '20', 'Electric', 'None', '1', 63, 1),
(80, 'Cloyster', 2, 2, 'Bivalve Pokémon, evolves from Shellder', 'Spike Cannon', '30x', 'Electric', 'None', '2', 22, 1),
(70, 'Tentacool', 2, 1, 'Jellyfish Pokémon, Base Set', 'Acid', '10', 'Electric', 'None', '1', 62, 1),
(80, 'Tentacruel', 2, 2, 'Jellyfish Pokémon, evolves from Tentacool', 'Supersonic', '—', 'Electric', 'None', '2', 43, 1),
(90, 'Hitmonlee', 3, 1, 'Kicking Pokémon, Fossil set rare', 'Stretch Kick', '30', 'Psychic', 'None', '2', 7, 3),
(100, 'Chansey', 3, 1, 'Egg Pokémon, Base Set rare', 'Double-Edge', '80', 'Fighting', 'None', '1', 3, 1);
